name: publish to PyPI
on: 
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/command-system/
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'
    - name: Install dependencies
      run: | 
        uv sync --locked --all-extras
    - name: Build package
      run: |
        uv build
    - name: Publish to PyPI
      run: |
        uv publish 
    