name: run pytest

on:
  pull_request:
    branches: [ "**" ]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
    - name: Setup python
      uses: actions/setup-python@v5
      with:
          python-version-file: '.python-version'
          cache: 'uv'
    - name: Install dependencies
      run: | 
        uv sync --locked --all-extras --dev
    - name: Run pytest
      run: |
        uv run pytest --cov